apiVersion: apps/v1
kind: Deployment
metadata:
  name: goviolin-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goviolin
  template:
    metadata:
      labels:
        app: goviolin
    spec:
      containers:
      - name: goviolin
        image: mostafahelal/goviolion
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: goviolin-service
spec:
  type: LoadBalancer
  selector:
    app: goviolin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
